# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = ""
language = "javascript"
manifest_version = 3
name = "cf-steam"
service_id = ""

[local_server]

[scripts]
  build = "npm run fastly:build"
  post_init = "npm install"
